Cries:
; entries correspond to CRY_* constants (see constants/cry_constants.asm)
	table_width 3
	dba Cry_Nidoran_M
	dba Cry_Nidoran_F
	dba Cry_Slowpoke
	dba Cry_Kangaskhan
	dba Cry_Charmander
	dba Cry_Grimer
	dba Cry_Voltorb
	dba Cry_Muk
	dba Cry_Oddish
	dba Cry_Raichu
	dba Cry_Nidoqueen
	dba Cry_Diglett
	dba Cry_Seel
	dba Cry_Drowzee
	dba Cry_Pidgey
	dba Cry_Bulbasaur
	dba Cry_Spearow
	dba Cry_Rhydon
	dba Cry_Golem
	dba Cry_Blastoise
	dba Cry_Pidgeotto
	dba Cry_Weedle
	dba Cry_Caterpie
	dba Cry_Ekans
	dba Cry_Fearow
	dba Cry_Clefairy
	dba Cry_Venonat
	dba Cry_Lapras
	dba Cry_Metapod
	dba Cry_Squirtle
	dba Cry_Paras
	dba Cry_Growlithe
	dba Cry_Krabby
	dba Cry_Psyduck
	dba Cry_Rattata
	dba Cry_Vileplume
	dba Cry_Vulpix
	dba Cry_Weepinbell
	dba Cry_Marill
	dba Cry_Spinarak
	dba Cry_Togepi
	dba Cry_Girafarig
	dba Cry_Raikou
	dba Cry_Mareep
	dba Cry_Togetic
	dba Cry_Hoothoot
	dba Cry_Sentret
	dba Cry_Slowking
	dba Cry_Cyndaquil
	dba Cry_Chikorita
	dba Cry_Totodile
	dba Cry_Gligar
	dba Cry_Cleffa
	dba Cry_Slugma
	dba Cry_Ledyba
	dba Cry_Entei
	dba Cry_Wooper
	dba Cry_Mantine
	dba Cry_Typhlosion
	dba Cry_Natu
	dba Cry_Teddiursa
	dba Cry_Sunflora
	dba Cry_Ampharos
	dba Cry_Magcargo
	dba Cry_Pichu
	dba Cry_Aipom
	dba Cry_Dunsparce
	dba Cry_Donphan
; gen 3 - all reference Bulbasaur's channel data
	dba Cry_Treecko
	dba Cry_Torchic
	dba Cry_Mudkip
	dba Cry_Poochyena
	dba Cry_Zigzagoon
	dba Cry_Wurmple
	dba Cry_Lotad
	dba Cry_Seedot
	dba Cry_Taillow
	dba Cry_Wingull
	dba Cry_Ralts
	dba Cry_Surskit
	dba Cry_Shroomish
	dba Cry_Slakoth
	dba Cry_Nincada
	dba Cry_Whismur
	dba Cry_Makuhita
	dba Cry_Azurill
	dba Cry_Nosepass
	dba Cry_Skitty
	dba Cry_Sableye
	dba Cry_Mawile
	dba Cry_Aron
	dba Cry_Meditite
	dba Cry_Electrike
	dba Cry_Plusle
	dba Cry_Minun
	dba Cry_Volbeat
	dba Cry_Illumise
	dba Cry_Roselia
	dba Cry_Gulpin
	dba Cry_Carvanha
	dba Cry_Wailmer
	dba Cry_Numel
	dba Cry_Torkoal
	dba Cry_Spoink
	dba Cry_Spinda
	dba Cry_Trapinch
	dba Cry_Cacnea
	dba Cry_Swablu
	dba Cry_Zangoose
	dba Cry_Seviper
	dba Cry_Lunatone
	dba Cry_Solrock
	dba Cry_Barboach
	dba Cry_Corphish
	dba Cry_Baltoy
	dba Cry_Lileep
	dba Cry_Anorith
	dba Cry_Feebas
	dba Cry_Castform
	dba Cry_Kecleon
	dba Cry_Shuppet
	dba Cry_Duskull
	dba Cry_Tropius
	dba Cry_Chimecho
	dba Cry_Absol
	dba Cry_Wynaut
	dba Cry_Snorunt
	dba Cry_Spheal
	dba Cry_Clamperl
	dba Cry_Relicanth
	dba Cry_Luvdisc
	dba Cry_Bagon
	dba Cry_Beldum
	dba Cry_Regirock
	dba Cry_Regice
	dba Cry_Registeel
	dba Cry_Latias
	dba Cry_Latios
	dba Cry_Kyogre
	dba Cry_Groudon
	dba Cry_Rayquaza
	dba Cry_Jirachi
	dba Cry_Deoxys
	assert_table_length NUM_CRIES
